verbose: true
go:
  version: 1.11.2
  cgo: false
repository:
  path: github.com/pdf/zfs_exporter
build:
  prefix: .build
  binaries:
    - name: zfs_exporter
  flags: -a -tags netgo
  ldflags: |
    -s
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
  prefix: .build
  files:
    - LICENSE
crossbuild:
  platforms:
    - linux/amd64
    - linux/386
    - freebsd/amd64
    - freebsd/386
    - solaris/amd64
    - solaris/386
    - darwin/amd64
    - darwin/386
